/* Auto-generated by tools/ui/generate_system_icons.py. Do not edit. */
#pragma once

#include "lvgl.h"

extern const lv_image_dsc_t cart_system_icon_gallery_dsc;
extern const lv_image_dsc_t cart_system_icon_gamepad_dsc;
extern const lv_image_dsc_t cart_system_icon_extensions_dsc;
extern const lv_image_dsc_t cart_system_icon_settings_dsc;
extern const lv_image_dsc_t cart_system_icon_sleep_dsc;
