#include "cmsis_os2.h"
#include "stm32h7xx.h"

/*
 * The FreeRTOS CMSIS-RTOS2 adapter generated by CubeMX only creates detached
 * threads and rejects osThreadJoinable. Newer CMSIS headers still declare
 * osThreadDetach(), which LVGL calls before terminating a thread.
 */
__WEAK osStatus_t osThreadDetach(osThreadId_t thread_id)
{
    if (__get_IPSR() != 0u) {
        return osErrorISR;
    }
    if (thread_id == NULL) {
        return osErrorParameter;
    }
    return osOK;
}
