#!/usr/bin/env python3
"""Generate the fixed 40x40 LVGL A8 Launcher system icon resources."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path


ICON_SIZE = 40
ICONS = (
    ("gallery", "library-photo.svg"),
    ("gamepad", "device-gamepad-2.svg"),
    ("extensions", "puzzle.svg"),
    ("settings", "settings.svg"),
    ("sleep", "moon.svg"),
)

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SOURCE_DIR = PROJECT_ROOT / "Core/Screen/Assets/Icons/Tabler"
OUTPUT_DIR = PROJECT_ROOT / "Core/Screen/Assets"
OUTPUT_HEADER = OUTPUT_DIR / "cart_system_icons_data.h"
OUTPUT_SOURCE = OUTPUT_DIR / "cart_system_icons_data.c"


def rasterize_svg(convert: str, source: Path) -> bytes:
    svg_data = source.read_bytes()
    if b'currentColor' not in svg_data:
        raise RuntimeError(f"missing currentColor stroke in {source.name}")

    # ImageMagick's SVG backends do not consistently resolve currentColor.
    # Resolve it in memory only; the checked-in official SVG stays unchanged.
    svg_data = svg_data.replace(b'currentColor', b'#000000')
    command = (
        convert,
        "-background", "none",
        "-density", "384",
        "svg:-",
        "-resize", f"{ICON_SIZE}x{ICON_SIZE}!",
        "-alpha", "extract",
        "-depth", "8",
        "gray:-",
    )
    result = subprocess.run(command, input=svg_data, check=False, capture_output=True)
    if result.returncode != 0:
        message = result.stderr.decode("utf-8", errors="replace").strip()
        raise RuntimeError(f"failed to rasterize {source.name}: {message}")
    expected_size = ICON_SIZE * ICON_SIZE
    if len(result.stdout) != expected_size:
        raise RuntimeError(
            f"unexpected A8 size for {source.name}: "
            f"expected {expected_size}, got {len(result.stdout)}"
        )
    return result.stdout


def format_bytes(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return "\n".join(rows)


def generate_header() -> str:
    declarations = "\n".join(
        f"extern const lv_image_dsc_t cart_system_icon_{name}_dsc;"
        for name, _ in ICONS
    )
    return f"""/* Auto-generated by tools/ui/generate_system_icons.py. Do not edit. */
#pragma once

#include "lvgl.h"

{declarations}
"""


def generate_source(images: dict[str, bytes]) -> str:
    blocks = []
    for name, _ in ICONS:
        blocks.append(
            f"""LV_ATTRIBUTE_MEM_ALIGN
static const uint8_t cart_system_icon_{name}_map[] = {{
{format_bytes(images[name])}
}};

const lv_image_dsc_t cart_system_icon_{name}_dsc = {{
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.cf = LV_COLOR_FORMAT_A8,
    .header.w = {ICON_SIZE},
    .header.h = {ICON_SIZE},
    .header.stride = {ICON_SIZE},
    .data_size = sizeof(cart_system_icon_{name}_map),
    .data = cart_system_icon_{name}_map,
}};"""
        )
    body = "\n\n".join(blocks)
    return f"""/*
 * Auto-generated from Tabler Icons SVG assets.
 *
 * Source: https://github.com/tabler/tabler-icons
 * License: MIT
 *
 * A8 stores coverage only; the Launcher supplies the visible color via style.
 * Do not edit this file manually.
 */

#include "cart_system_icons_data.h"

{body}
"""


def main() -> int:
    convert = shutil.which("convert")
    if convert is None:
        print(
            "error: ImageMagick 'convert' is required to rasterize the SVG assets",
            file=sys.stderr,
        )
        return 1

    missing = [str(SOURCE_DIR / filename) for _, filename in ICONS
               if not (SOURCE_DIR / filename).is_file()]
    if missing:
        print("error: missing input SVG assets:", file=sys.stderr)
        for path in missing:
            print(f"  {path}", file=sys.stderr)
        return 1

    try:
        images = {
            name: rasterize_svg(convert, SOURCE_DIR / filename)
            for name, filename in ICONS
        }
    except RuntimeError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_HEADER.write_text(generate_header(), encoding="utf-8", newline="\n")
    OUTPUT_SOURCE.write_text(generate_source(images), encoding="utf-8", newline="\n")
    print(f"generated {len(ICONS)} LVGL A8 icons at {ICON_SIZE}x{ICON_SIZE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
